frontendImage: "ghcr.io/aisalkyn85/kafka-enterprise-orders/frontend:latest"
backendImage: "ghcr.io/aisalkyn85/kafka-enterprise-orders/backend:latest"

backendPort: 8000

domain: "orders.jumptotech.dev"

couchbase:
  host: "couchbase.your-domain"
  bucket: "order_analytics"
  username: "Administrator"
  password: "password"

