frontendImage: "ghcr.io/aisalkyn85/kafka-enterprise-orders/web-frontend:latest"
backendImage: "ghcr.io/aisalkyn85/kafka-enterprise-orders/web-backend:latest"
backendPort: 8000

replicaCount: 1

ghcr:
  enabled: false
  username: "aisalkyn85"
  password: ""

ingress:
  host: "orders.jumptotech.net"
  certificateArn: "arn:aws:acm:us-east-2:343218219153:certificate/00353776-9755-4283-98f8-e05c1e337b28"

couchbase:
  host: "couchbase.your-domain.com"
  bucket: "order_analytics"
  username: "Administrator"
  password: ""
