apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orders-tls
  namespace: default
spec:
  secretName: orders-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - orders.jumptotech.net
