apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      labels:
        app: webapp

    spec:
      imagePullSecrets:
        - name: ghcr

      containers:
        # ----------------------------------------------------
        # FRONTEND (React + Nginx)
        # ----------------------------------------------------
        - name: frontend
          image: {{ .Values.frontendImage }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80

        # ----------------------------------------------------
        # BACKEND (FastAPI)
        # ----------------------------------------------------
        - name: backend
          image: {{ .Values.backendImage }}
          imagePullPolicy: Always

          env:
            - name: COUCHBASE_HOST
              value: "{{ .Values.couchbase.host }}"
            - name: COUCHBASE_BUCKET
              value: "{{ .Values.couchbase.bucket }}"
            - name: COUCHBASE_USERNAME
              value: "{{ .Values.couchbase.username }}"
            - name: COUCHBASE_PASSWORD
              value: "{{ .Values.couchbase.password }}"

          ports:
            - containerPort: {{ .Values.backendPort }}

