name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  AWS_REGION: us-east-2
  AWS_DEFAULT_REGION: us-east-2
  TF_VAR_aws_region: us-east-2
  TF_VAR_project_name: kafka-enterprise-orders

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Log in GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Normalize username
      - name: Normalize username
        run: echo "USERNAME_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      #############################
      # BUILD & PUSH IMAGES
      #############################

      - name: Build and push Producer
        run: |
          docker build -t ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-producer:latest producer
          docker push ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-producer:latest

      - name: Build and push Fraud Service
        run: |
          docker build -t ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-fraud-service:latest consumers/fraud-service
          docker push ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-fraud-service:latest

      - name: Build and push Payment Service
        run: |
          docker build -t ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-payment-service:latest consumers/payment-service
          docker push ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-payment-service:latest

      - name: Build and push Analytics Service
        run: |
          docker build -t ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-analytics-service:latest consumers/analytics-service
          docker push ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-analytics-service:latest

      - name: Build and push Web Backend
        run: |
          docker build -t ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-web-backend:latest web/backend
          docker push ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-web-backend:latest

      - name: Build and push Web Frontend
        run: |
          docker build -t ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-web-frontend:latest web/frontend
          docker push ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-web-frontend:latest

      #############################
      # TERRAFORM
      #############################

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/terraform
        env:
          TF_VAR_container_image_producer: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-producer:latest
          TF_VAR_container_image_fraud: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-fraud-service:latest
          TF_VAR_container_image_payment: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-payment-service:latest
          TF_VAR_container_image_analytics: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-analytics-service:latest
          TF_VAR_container_image_backend: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-web-backend:latest
          TF_VAR_container_image_frontend: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-web-frontend:latest
          TF_VAR_confluent_bootstrap_servers: ${{ secrets.CONFLUENT_BOOTSTRAP_SERVERS }}
          TF_VAR_confluent_api_key: ${{ secrets.CONFLUENT_API_KEY }}
          TF_VAR_confluent_api_secret: ${{ secrets.CONFLUENT_API_SECRET }}
          TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra/terraform
        env:
          TF_VAR_container_image_producer: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-producer:latest
          TF_VAR_container_image_fraud: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-fraud-service:latest
          TF_VAR_container_image_payment: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-payment-service:latest
          TF_VAR_container_image_analytics: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-analytics-service:latest
          TF_VAR_container_image_backend: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-web-backend:latest
          TF_VAR_container_image_frontend: ghcr.io/${{ env.USERNAME_LOWER }}/kafka-enterprise-orders-web-frontend:latest
          TF_VAR_confluent_bootstrap_servers: ${{ secrets.CONFLUENT_BOOTSTRAP_SERVERS }}
          TF_VAR_confluent_api_key: ${{ secrets.CONFLUENT_API_KEY }}
          TF_VAR_confluent_api_secret: ${{ secrets.CONFLUENT_API_SECRET }}
          TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}
        run: terraform apply -auto-approve tfplan

